import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import  { Roboto } from "next/font/google";
import {Navbar} from "@/app/sections/navbar";
import {ThemeProvider} from "@/components/ui/theme-provider";

const roboto = Roboto({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
      <ThemeProvider attribute="class" forcedTheme={"light"} enableSystem={false} disableTransitionOnChange>
          <Navbar/>
          <p className={"max-sm:w-[85%] text-center mx-auto my-[15px]"}>You can get 10% discount when you purchase more than 10 products and get fast free delivery.</p>
          {children}
      </ThemeProvider>
      </body>
    </html>
  );
}

